ecommerce_payment/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

ecommerce_payment/checkout/urls.py
from django.urls import include, path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('deliverychoices', views.deliverychoices, name='deliverychoices'),
    path('cart_update_delivery', views.cart_update_delivery, name='cart_update_delivery'),
    path('delivery_address', views.delivery_address, name='delivery_address'),
    path('payment_selection', views.payment_selection, name='payment_selection'),
    path('payment_complete', views.payment_complete, name='payment_complete'),
    path('payment_successful', views.payment_successful, name='payment_successful'),
]

ecommerce_payment/ecom/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_payment/cart/models.py
from django.db import models

# Create your models here.

ecommerce_payment/cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from shop.models import Product
from django.http import JsonResponse

def cart_summary(request):
    cart = Cart(request)
    context = {'cart': cart}
    return render(request, 'cart/summary.html', context)

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':    
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)

        cartqty = cart.__len__()
        response = JsonResponse({'qty':cartqty})
        return response 

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':    
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':    
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        cart.update(product=product_id, qty=product_qty)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response

ecommerce_payment/templates/cart/summary.html
{% extends "base.html" %}
{% load static %}
{% block title %} Cart Summary {% endblock %}

{% block content %}
    <div class="container">
        <div class="col-12">
            <h1 class="h2">Your Cart
            </h1>
        </div>
        <div class="col-12">
            <p>Manage your <b>items</b></p>
        </div>
        <hr />
    </div>
    <!-- Cart -->
    <div class="container">  
        <div class="row g-3">
            <!-- Check Empty -->
            {% if cart|length == 0 %}
            <div class="col-12">Your Cart is Empty, return <a href="/">home</a></div>
            {% else %}
            <div class="col-12 bg-light p-3 d-flex justify-content-between">
                <div class="d-flex d-flex-inline">
                <div class="pe-3">Order</div>
            </div>

        {% comment %}
        REQUIRES ADDRESS/DELIVERY OPTIONS
        <!-- Amount Owed -->    
        <div class="text-end">
            <div class="">Subtotal: <span class="fw-bold">$</span><div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div></div>
            <div id="">Shipping: <span class="fw-bold">$14.50</span></div>
            <div class="pt-2">Total: <span class="fw-bold h5">$</span><span id="total" class="fw-bold h5">{{cart.get_total_price}}</span></div></div>
        </div>
        <!-- Checkout -->
        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
            <div class="d-grid gap-2 ">
                <a role="button" href="{% url "checkout:deliverychoices" %}" class="btn btn-success fw-bold" type="button">Checkout</a>
            </div>
        </div>
        {% endcomment %}

        <!-- Amount Owed -->    
        <div class="text-end">
            <div class="">Subtotal: <span class="fw-bold">$</span><div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div></div>
            <div id="">Shipping: <span class="fw-bold">$14.50</span></div>
            <div class="pt-2">Total: <span class="fw-bold h5">$</span><span id="total" class="fw-bold h5">{{cart.get_total_price}}</span></div></div>
        </div>
        <!-- Checkout -->
        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
            <div class="d-grid gap-2 ">
                <a role="button" href="{% url "checkout:payment_selection" %}" class="btn btn-success fw-bold" type="button">Checkout</a>
            </div>
        </div>

        <!-- Cart Items -->
        <div class="col-md-7 col-lg-8 p-0">
            {% for item in cart %} 
            {% with product=item.product %}
            <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
                <div class="row g-0">
                    <div class="col-md-2 d-none d-md-block">
                        <!-- Loop Through images available in product -->
                        {% for image in product.product_image.all %}
                        {% if image.is_feature %}
                            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">

                        {% endif %}
                        {% endfor %}                    
                    </div>
                    <div class="col-md-10 ps-md-3">
                        <div class="card-body p-1">
                            <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                            <p class="card-text pb-3">{{product.name}}</p>
                            </a>
                        <label for="select">Qty</label>
                            <select id="select{{product.id}}" style="width:50px;height:31px;">
                                <option value="" selected disabled hidden>{{item.qty}}</option>
                                <option value="">1</option>
                                <option value="">2</option>
                                <option value="">3</option>
                                <option value="">4</option>
                            </select>
                            <a type="button" id="update-button" data-index="{{product.id}}" class="update-button text-decoration-none small ps-3">Update</a>
                            <a type="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none small">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endwith %} 
            {% endfor %}
        </div>
        {% endif %}
    </div>

<script>
    // Delete Item
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                // select product-item div, and delete the item off it 
                $('.product-item[data-index="' + prodid + '"]').remove();
                if(json.qty == 0) {
                    total = 0
                    subtotal = 0
                }
                else {
                    total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
                    subtotal = json.subtotal
                }
                document.getElementById("cart-qty").innerHTML = json.qty
                document.getElementById("subtotal").innerHTML = json.subtotal
                document.getElementById("total").innerHTML = total;                
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    // Update Item
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("cart-qty").innerHTML = json.qty
                document.getElementById("subtotal").innerHTML = json.subtotal
                total = (parseFloat(json.subtotal) + 14.50).toFixed(2);                
                document.getElementById("total").innerHTML = total;
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock %}