ecommerce_payment/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

ecommerce_payment/ecom/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_payment/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_all, name='shop_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

ecommerce_payment/shop/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext_lazy as _ # if you want intenationalization

"""DB Schema using MPTT (modified preorder tree traversal: efficient, but more involved while moving itmes around)"""

class Category(MPTTModel):
    # Schema
    name = models.CharField(
        verbose_name=_('Category Name'),    # lowercase will need to be addressed
        help_text=_("Required and Unique"), # will be under input form in admin area
        max_length=255,
        unique=True,
    )

    slug = models.SlugField(verbose_name=_("Category safe URL"), max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)   # Category maybe disabled if needed

    class MPTTMeta:
        order_insertion_by = ["name"]

    # for admin area
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse("shop:category_list", args=[self.slug])

    def __str__(self):
        return self.name    

class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(verbose_name=_("Product Name"), help_text=_("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name

class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specifiction or features for the product types.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name

class Product(models.Model):
    """
    Table for all product items.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    description = models.TextField(verbose_name=_("description"), help_text=_("Not Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )

    # in case for discount event
    discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )

    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )

    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.slug])

    def __str__(self):
        return self.name

class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")        # Use Foreignkey for Product Images
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)                                                     # featured image
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

ecommerce_payment/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product 

def product_all(request):
#    products = Product.objects.all()
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)   # optimization for indexing

    context = {'products': products}

    return render(request, 'shop/index.html', context)

def category_list(request, category_slug):
    # get subcategories of each category using MPTT
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(
        category__in=Category.objects.get(name=category_slug).get_descendants(include_self=True)
    )

    context = {'category': category,
               'products': products, }

    return render(request, 'shop/category.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, is_active=True)
    context = {'product': product}

    return render(request, 'shop/single.html', context)

ecommerce_payment/templates/shop/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<!-- Header -->
<div class="container">
    <div class="col-12">
        <h1 class="h2">{{ category.name | title }}</h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
        <div><b>Popular</b> Images</div>
    </div>
    <hr />
</div>

<div class="container">
    <div class="row">
        <div class="album">
            {% if not products %}
            <div class="col-12">No images Available! return <a href="{% url 'shop:shop_home' %}">Home</a></div>
            {% else %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                <div class="col">
                    <div class="card border-0">
                        <!-- Loop Through images available in product -->
                        {% for image in product.product_image.all %}
                        {% if image.is_feature %}
                            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                        {% endif %}
                        {% endfor %}
                        <div class="card-body px-0">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none"
                                    href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">${{ product.regular_price }}</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

ecommerce_payment/templates/shop/index.html
{% extends "../base.html" %}
{% block title %}Shop{% endblock %}
{% block content %}

<div class="container">
	<div class="container">
		<div class="row">
			<div class="album py-5">
				<div class="pb-3">
					<h1 class="h3">Available</h1>
				</div>
				{% if not products %}
				<div class="col-12">There are currently no products active</div>
				{% else %}
				<div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
					{% for product in products %}
					<div class="col">
						<div class="card border-0">
							<!-- Loop Through images available in product -->
							{% for image in product.product_image.all %}
							{% if image.is_feature %}
								<img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">

							{% endif %}
							{% endfor %}
							<div class="card-body px-0">
								<p class="card-text">
									<a class="text-dark text-decoration-none"
										href="{{ product.get_absolute_url }}">{{ product.name }}</a>
								</p>
								<div class="fw-bold">${{product.regular_price}}</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

ecommerce_payment/templates/shop/single.html
{% extends "../base.html" %}
{% load static %}
{% block stylesheet %}{% static 'shop/css/shop.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.name }}{% else %}Product{% endif %}
{% endblock %}
{% block content %}

<div class="container">
    <div class="row g-3">
        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grid gap-2">
                <div class="d-flex d-flex-inline justify-content-between">
                    <div><span class="h3">${{ product.regular_price }}</span>
                        <p class="text-muted">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    </div>
                    <div>
                        <label for="select">Qty</label>
                        <select id="select" class="h6 shop-select-dropdown">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                        </select>
                    </div>
                </div>
                <hr>
                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
                    cart</button>
                <!-- Favorite 
                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Add to
                    Favorites</button>
                -->                    
            </div>
        </div>
        <div class="col-md-7 col-lg-7 p-0">
            <div class="card mb-3 border-0">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-body p-1">
                            <h1 class="mb-0 h2 pe-4 pb-4">{{ product.name }}</h1>
                            <!-- go through image available for product -->
                            <!-- maybe implement, so you can go for enhanced view when you click the image-->
                            <!-- Featured item must be at top, regardless of position of image in image repo -->
                            <div class="bg-light">
                            {% for image in product.product_image.all %}
                                {% if image.is_feature %}
                                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{image.image.url}}" alt="{{image.alt_text}}">
                                {% else %}
                                    <img class="img-fluid d-block-inline pt-3" width="100px" alt="Responsive image" src="{{image.image.url}}" alt="{{image.alt_text}}">
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- script for add to cart function -->
<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById('cart-qty').innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}

        });
    })
</script>

{% endblock %}